# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-12 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(help_text='供应商名称', max_length=30, verbose_name='供应商名称')),
                ('buy_way', models.CharField(help_text='采购渠道', max_length=20, verbose_name='采购渠道')),
                ('qq', models.CharField(blank=True, default='', help_text='联系qq号码', max_length=20, null=True, verbose_name='联系qq号码')),
                ('phone', models.CharField(blank=True, default='', help_text='联系电话', max_length=20, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', help_text='地址', max_length=100, null=True, verbose_name='地址')),
                ('store_url', models.CharField(blank=True, default='', help_text='店铺链接', max_length=300, null=True, verbose_name='店铺链接')),
                ('note', models.TextField(blank=True, default='', help_text='备注', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '供应商信息',
                'ordering': ['-create_time'],
                'verbose_name_plural': '供应商信息',
            },
        ),
    ]
