# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.BooleanField(default=True, help_text='启用状态', verbose_name='启用状态'),
        ),
    ]
