# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180623_1705'),
        ('product', '0002_supplier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(help_text='公司', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Company', verbose_name='公司'),
        ),
    ]
