# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-24 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_combopack_combosku_product_regcountry_regproduct_vcombo_vsku'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='产品编码', max_length=30, verbose_name='产品编码')),
                ('buy_url', models.CharField(blank=True, help_text='采购链接', max_length=300, null=True, verbose_name='采购链接')),
                ('primary_supplier', models.BooleanField(default=False, help_text='默认供应商', verbose_name='默认供应商')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('supplier', models.ForeignKey(help_text='供应商', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商产品',
                'verbose_name_plural': '供应商产品',
                'ordering': ['-create_time'],
            },
        ),
    ]
