# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-24 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_supplierproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='regcountry',
            name='reg_product',
            field=models.ForeignKey(help_text='对应注册产品', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.RegProduct', verbose_name='对应注册产品'),
        ),
    ]
