# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-24 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_regcountry_reg_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='product',
            field=models.ForeignKey(help_text='产品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sup_product', to='product.Product', verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='combosku',
            name='combo_pack',
            field=models.ForeignKey(help_text='组合产品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_pack_sku', to='product.ComboPack', verbose_name='组合产品'),
        ),
        migrations.AlterField(
            model_name='regcountry',
            name='reg_product',
            field=models.ForeignKey(help_text='对应注册产品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_product_reg_country', to='product.RegProduct', verbose_name='对应注册产品'),
        ),
        migrations.AlterField(
            model_name='regproduct',
            name='product',
            field=models.ForeignKey(help_text='对应产品', on_delete=django.db.models.deletion.CASCADE, related_name='product_reg_product', to='product.Product', verbose_name='对应产品'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(help_text='供应商', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sup_product', to='product.Supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='vcombo',
            name='combo_pack',
            field=models.ForeignKey(help_text='组合产品', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combo_pack_vcombo', to='product.ComboPack', verbose_name='组合产品'),
        ),
        migrations.AlterField(
            model_name='vsku',
            name='product',
            field=models.ForeignKey(help_text='对应产品', on_delete=django.db.models.deletion.CASCADE, related_name='product_vsku', to='product.Product', verbose_name='对应产品'),
        ),
    ]
