# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-30 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180624_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regproduct',
            name='reg_heigth',
            field=models.FloatField(blank=True, help_text='确认高', null=True, verbose_name='确认高'),
        ),
        migrations.AlterField(
            model_name='regproduct',
            name='reg_length',
            field=models.FloatField(blank=True, help_text='确认长', null=True, verbose_name='确认长'),
        ),
        migrations.AlterField(
            model_name='regproduct',
            name='reg_volume',
            field=models.FloatField(blank=True, help_text='确认体积', null=True, verbose_name='确认体积'),
        ),
        migrations.AlterField(
            model_name='regproduct',
            name='reg_weight',
            field=models.FloatField(blank=True, help_text='确认重量', null=True, verbose_name='确认重量'),
        ),
        migrations.AlterField(
            model_name='regproduct',
            name='reg_width',
            field=models.FloatField(blank=True, help_text='确认宽', null=True, verbose_name='确认宽'),
        ),
    ]
