# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-05 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180630_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='sku',
        ),
    ]
