# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-08 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_supplierproduct_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, help_text='商品URL', max_length=200, null=True, verbose_name='商品URL'),
        ),
    ]
