# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-09 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20180708_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='combosku',
            name='combo_status',
            field=models.BooleanField(default=True, help_text='启用状态', verbose_name='启用状态'),
        ),
    ]
