# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-15 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20180715_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regcountry',
            name='reg_status',
            field=models.CharField(choices=[('ON_SALE', '已发布'), ('CHECKING', '待审核'), ('REGING', '注册中'), ('FAIL', '审核失败')], help_text='产品注册状态', max_length=10, verbose_name='产品注册状态'),
        ),
    ]
