# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-21 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20180715_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ON_SALE', '在售'), ('OFFLINE', '停售'), ('CLEAN', '清仓中'), ('UNKNOWN', '自动创建')], default='ON_SALE', help_text='产品状态', max_length=10, verbose_name='产品状态'),
        ),
    ]
