# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-21 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20180721_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='buy_way',
            field=models.CharField(blank=True, help_text='采购渠道', max_length=20, null=True, verbose_name='采购渠道'),
        ),
    ]
