# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-01 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0007_auto_20180913_2343'),
        ('users', '0003_company_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillPromote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_qty', models.IntegerField(default=0, help_text='推荐采购数量', verbose_name='推荐采购数量')),
                ('t_weight', models.FloatField(blank=True, help_text='单项重量kg', null=True, verbose_name='单项重量kg')),
                ('warehouse', models.ForeignKey(help_text='仓库', on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse', verbose_name='仓库')),
                ('warehouse_stock', models.ForeignKey(help_text='仓库库存', on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseStock', verbose_name='仓库库存')),
            ],
            options={
                'verbose_name': '补货推荐',
                'verbose_name_plural': '补货推荐',
                'ordering': ['-buy_qty'],
            },
        ),
        migrations.CreateModel(
            name='RefillSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='是否开启', verbose_name='是否开启')),
                ('stock_days', models.IntegerField(default=0, help_text='库存备货天数', verbose_name='库存备货天数')),
                ('min_buy', models.IntegerField(default=0, help_text='最少采购个数', verbose_name='最少采购个数')),
                ('auto_carry', models.IntegerField(default=0, help_text='自动进位', verbose_name='自动进位')),
                ('is_auto_calc', models.BooleanField(default=True, help_text='是否自动计算', verbose_name='是否自动计算')),
                ('remind_weight', models.FloatField(blank=True, help_text='自动计算提醒重量', null=True, verbose_name='自动计算提醒重量')),
                ('remind_sku_qty', models.IntegerField(default=0, help_text='提醒商品SKU数', verbose_name='提醒商品SKU数')),
                ('remind_total_qty', models.IntegerField(default=0, help_text='提醒总商品数', verbose_name='提醒总商品数')),
                ('company', models.ForeignKey(help_text='公司', on_delete=django.db.models.deletion.CASCADE, to='users.Company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '补货推荐设置',
                'verbose_name_plural': '补货推荐设置',
            },
        ),
    ]
