# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-20 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsauth',
            name='app_key',
            field=models.CharField(blank=True, help_text='物流用户账号', max_length=50, null=True, verbose_name='物流用户账号'),
        ),
        migrations.AlterField(
            model_name='logisticsauth',
            name='token',
            field=models.CharField(blank=True, help_text='账户token', max_length=200, null=True, verbose_name='账户token'),
        ),
    ]
