# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-31 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_thirdwarehouse_wh_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirddelivery',
            name='is_active',
            field=models.BooleanField(default=False, help_text='是否激活', verbose_name='是否激活'),
        ),
    ]
