# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-08-30 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_company_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_code', models.CharField(help_text='仓位编码', max_length=50, verbose_name='仓位编码')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
            ],
            options={
                'verbose_name_plural': '仓位',
                'verbose_name': '仓位',
                'ordering': ['po_code'],
            },
        ),
        migrations.CreateModel(
            name='ThirdDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(help_text='派送方式代码', max_length=80, verbose_name='派送方式代码')),
                ('delivery_way', models.CharField(help_text='派送方式名称', max_length=200, verbose_name='派送方式名称')),
                ('origin_name', models.CharField(help_text='派送方式名称(原名称)', max_length=200, verbose_name='派送方式名称(原名称)')),
                ('delivery_id', models.CharField(help_text='派送方式id', max_length=30, verbose_name='派送方式id')),
                ('is_door_number', models.BooleanField(default=False, help_text='派送方式是否门牌必选', verbose_name='派送方式是否门牌必选')),
                ('wh_id', models.CharField(help_text='海外仓仓库id', max_length=30, verbose_name='海外仓仓库id')),
            ],
            options={
                'verbose_name_plural': '仓库物流派送方式',
                'verbose_name': '仓库物流派送方式',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wh_code', models.CharField(help_text='仓库代码', max_length=80, verbose_name='仓库代码')),
                ('wh_id', models.CharField(help_text='仓库ID', max_length=80, verbose_name='仓库ID')),
                ('wh_name', models.CharField(help_text='仓库名称', max_length=30, verbose_name='仓库名称')),
                ('return_name', models.CharField(blank=True, help_text='仓库退货收件人', max_length=80, null=True, verbose_name='仓库退货收件人')),
                ('return_phone', models.CharField(blank=True, help_text='仓库退货电话', max_length=30, null=True, verbose_name='仓库退货电话')),
                ('return_address', models.CharField(blank=True, help_text='仓库退货地址', max_length=200, null=True, verbose_name='仓库退货地址')),
                ('post_name', models.CharField(blank=True, help_text='仓库发货人姓名', max_length=80, null=True, verbose_name='仓库发货人姓名')),
                ('post_phone', models.CharField(blank=True, help_text='仓库发货人电话', max_length=30, null=True, verbose_name='仓库发货人电话')),
                ('post_address', models.CharField(blank=True, help_text='仓库发货地址', max_length=200, null=True, verbose_name='仓库发货地址')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('wh_type', models.CharField(choices=[('LOCAL', '本地仓'), ('OS', '海外仓')], default='OS', help_text='仓库类型', max_length=10, verbose_name='仓库类型')),
                ('country_code', models.CharField(blank=True, help_text='仓库所在国家代码', max_length=20, null=True, verbose_name='仓库所在国家代码')),
                ('logistics_company', models.CharField(help_text='物流公司', max_length=50, verbose_name='物流公司')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('company', models.ForeignKey(help_text='公司', on_delete=django.db.models.deletion.CASCADE, to='users.Company', verbose_name='公司')),
            ],
            options={
                'verbose_name_plural': '仓库列表',
                'verbose_name': '仓库列表',
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='产品sku编码', max_length=50, verbose_name='产品sku编码')),
                ('all_stock', models.IntegerField(default=0, help_text='总库存', verbose_name='总库存')),
                ('available_qty', models.IntegerField(default=0, help_text='可用库存(os)', verbose_name='可用库存(os)')),
                ('reserved_qty', models.IntegerField(default=0, help_text='待出库(os)', verbose_name='待出库(os)')),
                ('on_way_qty', models.IntegerField(default=0, help_text='在途库存(os)', verbose_name='在途库存(os)')),
                ('his_in_qty', models.IntegerField(default=0, help_text='历史入库数量(os)', verbose_name='历史入库数量(os)')),
                ('his_sell_qty', models.IntegerField(default=0, help_text='历史销量(os)', verbose_name='历史销量(os)')),
                ('avg_sell_qty', models.CharField(blank=True, help_text='近30天平均销量(os)', max_length=50, null=True, verbose_name='近30天平均销量(os)')),
                ('avg_stock', models.CharField(blank=True, help_text='近30天平均库存(os)', max_length=50, null=True, verbose_name='近30天平均库存(os)')),
                ('doi', models.CharField(blank=True, help_text='DOI(os)', max_length=50, null=True, verbose_name='DOI(os)')),
                ('is_return', models.BooleanField(default=False, help_text='是否退货库存(os)', verbose_name='是否退货库存(os)')),
                ('is_active', models.BooleanField(default=True, help_text='产品是否有效(os)', verbose_name='产品是否有效(os)')),
                ('is_prohibit', models.BooleanField(default=False, help_text='是否禁止出库(os)', verbose_name='是否禁止出库(os)')),
                ('is_onsale', models.BooleanField(default=True, help_text='是否在售', verbose_name='是否在售')),
                ('position', models.CharField(blank=True, help_text='仓位', max_length=50, null=True, verbose_name='仓位')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('warehouse', models.ForeignKey(help_text='仓库', on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name_plural': '仓库库存',
                'verbose_name': '仓库库存',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='thirddelivery',
            name='warehouse',
            field=models.ForeignKey(help_text='仓库', on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='position',
            name='warehouse',
            field=models.ForeignKey(help_text='仓库', on_delete=django.db.models.deletion.CASCADE, to='warehouse.Warehouse', verbose_name='仓库'),
        ),
    ]
