# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-11 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_warehouse_wh_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='cn_name',
            field=models.CharField(blank=True, help_text='产品名称', max_length=100, null=True, verbose_name='产品名称'),
        ),
    ]
