# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-13 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20180913_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousestock',
            name='avg_sell_qty',
            field=models.FloatField(blank=True, help_text='近30天平均销量(os)', null=True, verbose_name='近30天平均销量(os)'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='avg_sell_qty15',
            field=models.FloatField(blank=True, help_text='近15天平均销量(os)', null=True, verbose_name='近15天平均销量(os)'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='avg_sell_qty7',
            field=models.FloatField(blank=True, help_text='近7天平均销量(os)', null=True, verbose_name='近7天平均销量(os)'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='avg_stock',
            field=models.FloatField(blank=True, help_text='近30天平均库存(os)', null=True, verbose_name='近30天平均库存(os)'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='avg_stock15',
            field=models.FloatField(blank=True, help_text='近15天平均库存(os)', null=True, verbose_name='近15天平均库存(os)'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='avg_stock7',
            field=models.FloatField(blank=True, help_text='近7天平均库存(os)', null=True, verbose_name='近7天平均库存(os)'),
        ),
    ]
